main/urls.py
from django.urls import path
from main.views import inicio, frutas, verduras, descuento, contacto, Login, logout, UsuarioCrear, carrito, carro,eliminar_item

app_name = "main"

urlpatterns = [
	path("",inicio, name="inicio"), 
	path("frutas/", frutas, name="frutas"),
	path("verduras/", verduras, name="verduras"),
	path("descuento/",descuento, name="descuento"),
	path("contacto/", contacto, name="contacto"),
	path("login/", Login.as_view(), name="login"),
	path("logout/", logout, name="logout"),
	path("registrarse/", UsuarioCrear.as_view(), name="registrarse"),
	path("carrito/", carrito, name="carrito"),
	path("carro/",carro, name="carro"),
	path("eliminar/item/<int:pk>", eliminar_item, name="eliminar_item"),
]

revuelteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from revuelteria import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>carrito</title>
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{%static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{%static 'css/animate.css' %}" rel="stylesheet">
	<link href="{%static 'css/main.css' %}" rel="stylesheet">
	<link href="{%static 'css/responsive.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estilos1.css' %} ">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estilos3.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estilos5.css' %}">

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>

	{%include 'navigation.html'%}

		
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				</ol>
			</div >
				<div class="fondo">
				<div class="table-responsive cart_info">
					<table class="table table-condensed">
						<thead>
							<tr class="cart_menu">
								<td class="image">Item</td>
								<td class="description"></td>
								<td class="price">Precio</td>
								<td class="quantity">Cantidad</td>
								<td class="total">Total</td>
								<td></td>
							</tr>
						</thead>
						<tbody>
							{%for contenido in object_list%}
							<tr>							
								{%if contenido.verdura%}
								<td class="cart_product">
									<a href=""><img class="lo" src="{{contenido.verdura.imagen.url}}" alt=""></a>
								</td>
								<td class="cart_description">
									<h4><a href="">{{contenido.verdura.nombre}}</a></h4>
									<p>Web ID: {{contenido.verdura.pk}}</p>
								</td>
								<td class="cart_price">
									<p>{{contenido.verdura.precio}}</p>
								</td>
								{%else%}
								<td class="cart_product">
									<a href=""><img class="lo" src="{{contenido.fruta.imagen.url}}" alt=""></a>
								</td>
								<td class="cart_description">
									<h4><a href="">{{contenido.fruta.nombre}}</a></h4>
									<p>Web ID: {{contenido.fruta.pk}}</p>
								</td>
								<td class="cart_price">
									<p>{{contenido.fruta.precio}}</p>
								</td>
								{%endif%}
								
								<td class="cart_quantity">
									<div class="cart_quantity_button">
										<input class="cart_quantity_input" type="text" name="quantity" value="{{contenido.cantidad}}" autocomplete="off" size="2" disabled="">
									</div>
								</td>
								<td class="cart_total">
									<p class="cart_total_price">${{contenido.total_pagar}}</p>
								</td>
								<td class="cart_delete">
									<a class="cart_quantity_delete" href="{%url 'main:eliminar_item' contenido.pk%}"><i class="fa fa-times"></i></a>
								</td>
							</tr>
							{%endfor%}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section> <!--/#cart_items-->

	

templates/contacto.html
{%load static%}
<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <title>Frutas y Verduras</title>
                <link rel="stylesheet" href="{%static 'css/yeison.css' %}">
                <link rel="stylesheet" type="text/css" href="{%static 'css/estilos1.css'%} ">
                <link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
              </head>


<body>
	

	{%include 'navigation.html'%}

    <div id="lolo">
        <img src="{%static 'img/contactanos.jpg' %}" alt="servicio al cliente">
        <h3>Contamos con un servicio de de 9:a.m hasta las 9:p.m <br/>
            Dirección: Calle 41, #1102 primer piso <br/>
            Celular: 3124526911 <br/>
		</h3> <br/> <br/>
		
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3975.597983391334!2d-75.67498628555313!3d4.8388826417920034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3880dea3bbf511%3A0xed80aa175f81d686!2sCl.+41+%2311-2%2C+Dosquebradas%2C+Risaralda!5e0!3m2!1ses!2sco!4v1557760874677!5m2!1ses!2sco" width="800" height="450"  frameborder="0" style="border:0" allowfullscreen></iframe>


	</div>
	
	

    
    
</body>

</html>

templates/descuento.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>OFERTAS</title>
	<meta charset="utf-8">
	
	<link rel="stylesheet" href="{%static 'css/estilo.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estilos1.css'%} ">
	<link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


</head>
	
	</div>

<body>

	
	{%include 'navigation.html'%}
	<div id="lolo">
    <div class="cuerpo">
	<h1  class="of">OFERTAS</h1>


	<h2>Ofertas en verduras desde el 12 hasta el 29 de mayo; toda verdura que encuentres estara en oferta. Aprovecha hasta el maximo esta oportunidad.</h2><img src="{%static 'img/verduras.jpg' %}">
</br></br>

	<h2 ><b>¿Te gustan las manzanas?</b> aprovecha, este fin de semana podras llevar 2  manzanas màs por la compra de 3 no la dejes pasar.</h2><img src="{%static 'img/manz.jpg' %}"></br></br>

	<h2><b>35% de descuento en frutas y verduras por la compra de mas de 50.000 COP.</h2><img src="{%static 'img/oferta.jpg' %}"></br></br>


	
</div>
</div>
</body>
</html>

templates/fruteria.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>FRUTAS</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{%static 'css/styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estilos1.css'%} ">
	<link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
	{%include 'navigation.html'%}
	
	<div class="done">	
		<h1>FRUTAS</h1>
		<table>
			{% for contenido in object_list %}
				<td>
					<div class="banano">
						<img class="ban"src="#">
						<h2>{{contenido.nombre}}</h2>
						<p>L${{contenido.precio}}</p>
						<div id="ol">
						<button onclick="fruta({{contenido.pk}})" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">comprar</button>
						</div>
					</div>
				</td>
				{%if forloop.counter in li %}
					<tr>
				{%endif%}
				{%if forloop.counter in li %}
					</tr>
				{%endif%}

				
			{%endfor%}
		</table>
	</div>
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLabel">Carrito</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
		        <form name="data-carrito" method="POST" action="{%url 'main:carrito'%}">{%csrf_token%}
		        	<label class="form-control">Cantidad a comprar</label>
		        	<input type="hidden" name="producto" value="fruta">
		        	<input id="producto" type="hidden" name="id_producto">
		        	<input class="form-control" type="number" name="cantidad" value="0">
		        	<input type="submit" name="Guardar" class="btn btn-primary">
		        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		        </form>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script type="text/javascript">
	$('#myModal').on('shown.bs.modal', function () {
		  $('#myInput').trigger('focus')
		})
	</script>
	<script type="text/javascript">
		function fruta(id){
			console.log(id);
			var data = document.getElementById("producto");
			data.value=id;
		}
	</script>
</body>
</html>

templates/index.html
{%load static%}
<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <title>Frutas y Verduras</title>
				<link rel="stylesheet" href="{%static 'css/estilos.css' %}">
				<link rel="stylesheet" href="{%static 'css/nivo-slider.css' %}">
				<link rel="stylesheet" href="{%static 'css/mi-slider.css' %}">
				 <link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
				<link rel="stylesheet" type="text/css" href="{%static 'css/estilos1.css'%} ">
				<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
				
				<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>
				<script src="{%static 'js/jquery.nivo.slider.js' %}"></script>

				<script type="text/javascript"> 
					$(window).on('load', function() {
		    		$('#slider').nivoSlider(); 
					}); 
				</script>
        </head>


<body>
	

	{%include 'navigation.html'%}
	<div id="lolo">

		<div class="slider-wrapper theme-mi-slider">
			<div id="slider" class="nivoSlider">     
				<img src="{%static 'img/frutas1.jpg' %}" alt="" title="#htmlcaption1" />    
				<img src="{%static 'img/frutas2.jpg' %}" alt="" title="#htmlcaption2" />    
				<img src="{%static 'img/holi.jpg' %}" alt="" title="#htmlcaption3" />
				<img src="{%static 'img/agricultor.jpg' %}" alt="" title="#htmlcaption4" />     
			</div> 
			<div id="htmlcaption1" class="nivo-html-caption">     
				<h1>35% de descuento en fruta y verduras por la compra <br/>
					de productos con targeta de credito.</h1>
			</div>
			<div id="htmlcaption2" class="nivo-html-caption">     
				<h1> La frescura llega al verano.</h1>
			</div>
			<div id="htmlcaption3" class="nivo-html-caption">     
				<h1> Traído del mejor cultivo de Colombia</h1>
				<div id="htmlcaption4" class="nivo-html-caption">
					<h1>Traido del mejor cultivador de Colombia</h1>
				</div>
			</div>
		</div>
	</div>
        

    </div>

    
    
</body>

</html>

templates/login.html
{%load static%}
<!DOCTYPE html>
<html lang="es">
<head>
	 <meta charset="utf-8">
    <title>Iniciar Sesión</title>
    <meta name="viewport" content="width= device-width, user-scalable=yes, initial- scale= 1.0, maximum-scale=3.0, minimum-scale=1.0">
    <link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{%static 'css/style1.css' %}">
</head>
<body>
	<form class="formulario" method="POST" action="{%url 'main:login'%}">{%csrf_token%}
      <h1>Iniciar Sesión</h1> 
      <div class="contenedor">

        <div class="input-contenedor">
            <i class="fas fa-envelope-square icon"></i>
            <input id="id_username" name="username" type="text" placeholder="Correo Electronico" required>
        </div>

        <div class="input-contenedor">
            <i class="fas fa-lock icon"></i>
            <input id="id_password" name="password" type="password" placeholder="Contraseña" required>
        </div>

        <input type="submit" value="Iniciar Sesión" class="button">
        <p></p>
        <p>¿No tienes una cuenta? <a class="link" href="{% url 'main:registrarse' %}">Registrate</a></p>
      </div>
   </form> 
</body>
</html>

templates/navigation.html
{%load static%}
<header>
	<nav>
		<div>
			<ul class="nav">
				<li><a href="{%url 'main:inicio'%}">Inicio</a></li>
				<li><a href="#">servicios</a>
					 <ul>
						<li><a href="{% url 'main:frutas' %}">frutas</a></li>
						<li><a href="{% url 'main:verduras' %}">verduras</a></li>
						
					</ul>
				</li>
				<li><a href="{%url 'main:descuento' %}">descuentos</a></li>
				<li><a href="{%url 'main:contacto' %}">contactanos</a></li>
				<li><a href="{%url 'main:carro' %}" class="active"><i class="fa fa-shopping-cart"></i> Cart</a></li>
				<li style="padding-left: 740px"><a href="{%url 'main:logout'%}">cerrar sesion</a></li>
			</ul>
		</div>
	</nav>	
</header>

templates/registrarse.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Crear cuenta</title>
    <meta name="viewport" content="width= device-width, user-scalable=yes, initial- scale= 1.0, maximum-scale=3.0, minimum-scale=1.0">
    <link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>
<body>
   <form class="formulario" method="POST" action="{%url 'main:registrarse'%}"> {%csrf_token%}
      <h1>Crear cuenta</h1> 
      <div class="contenedor">

        <div class="input-contenedor">
            <i class="far fa-user icon"></i>
            <input id="field-2" name="first_name" type="text" placeholder="Nombre Completo">
        </div>

        <div class="input-contenedor">
            <i class="fas fa-envelope-square icon"></i>
            <input name="username" id="field-3" type="text" placeholder="Correo Electronico">
        </div>

        <div class="input-contenedor">
            <i class="fas fa-lock icon"></i>
            <input name="password1" id="field-4" type="password" placeholder="Contraseña">
        </div>

        <div class="input-contenedor">
            <i class="fas fa-lock icon"></i>
            <input name="password2" id="field-5" type="password" placeholder="Contraseña">
        </div>
        <input type="submit" value="Registrarte" class="button">
        <p>Al registrarte, aceptas nuestras condiciones de uso y politica de privacidad.</p>
        <p>¿Ya tienes una cuenta? <a class="link" href="{% url 'main:login' %}">Iniciar Sesiòn</a></p>
      </div>
   </form> 
</body>
</html>

templates/verduras.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>VERDURAS</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estiles.css'%} ">
	<link rel="stylesheet" type="text/css" href="{%static 'css/estilos1.css'%} ">
	<link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
	{%include 'navigation.html'%}
	<div class="done">	
		<h1>VERDURAS</h1>
		<table>
			{% for contenido in object_list %}
				<td>
					<div class="banano">
						<img class="ban"src="{{contenido.imagen.url}}">
						<h2>{{contenido.nombre}} {{forloop.counter}}</h2>
						<p>L${{contenido.precio}}</p>
						<div id="ol">
						<button onclick="verdura({{contenido.pk}})" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">comprar</button>
						</div>
					</div>
				</td>
				{%if forloop.counter in li %}
					<tr>
				{%endif%}
				{%if forloop.counter in li %}
					</tr>
				{%endif%}

				
			{%endfor%}
		</table>
		<!-- Modal -->
		
	</div>
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
		        <form name="data-carrito" method="POST" action="{%url 'main:carrito'%}">{%csrf_token%}
		        	<label class="form-control">Cantidad a comprar</label>
		        	<input type="hidden" name="producto" value="verdura">
		        	<input id="producto" type="hidden" name="id_producto">
		        	<input class="form-control" type="number" name="cantidad" value="0">
		        	<input type="submit" name="Guardar" class="btn btn-primary">
		        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		        </form>
		      </div>
		    </div>
		  </div>
		</div>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script type="text/javascript">
	$('#myModal').on('shown.bs.modal', function () {
		  $('#myInput').trigger('focus')
		})
	</script>
	<script type="text/javascript">
		function verdura(id){
			console.log(id);
			var data = document.getElementById("producto");
			data.value=id;
		}
	</script>
</body>
</html>